allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver

overrides:
  postcss: "8.5.15"
  "next>postcss": "8.5.15"
