# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import simulation_pb2 as simulation__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartMatchSimulation = channel.unary_unary(
                '/footex.simulation.SimulationService/StartMatchSimulation',
                request_serializer=simulation__pb2.SimulateMatchRequest.SerializeToString,
                response_deserializer=simulation__pb2.StartMatchResponse.FromString,
                _registered_method=True)
        self.StartMatchSimulationStream = channel.unary_stream(
                '/footex.simulation.SimulationService/StartMatchSimulationStream',
                request_serializer=simulation__pb2.SimulateMatchRequest.SerializeToString,
                response_deserializer=simulation__pb2.MatchEventRaw.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/footex.simulation.SimulationService/GetHealth',
                request_serializer=simulation__pb2.HealthRequest.SerializeToString,
                response_deserializer=simulation__pb2.HealthResponse.FromString,
                _registered_method=True)


class SimulationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartMatchSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMatchSimulationStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartMatchSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMatchSimulation,
                    request_deserializer=simulation__pb2.SimulateMatchRequest.FromString,
                    response_serializer=simulation__pb2.StartMatchResponse.SerializeToString,
            ),
            'StartMatchSimulationStream': grpc.unary_stream_rpc_method_handler(
                    servicer.StartMatchSimulationStream,
                    request_deserializer=simulation__pb2.SimulateMatchRequest.FromString,
                    response_serializer=simulation__pb2.MatchEventRaw.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=simulation__pb2.HealthRequest.FromString,
                    response_serializer=simulation__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'footex.simulation.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('footex.simulation.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartMatchSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/footex.simulation.SimulationService/StartMatchSimulation',
            simulation__pb2.SimulateMatchRequest.SerializeToString,
            simulation__pb2.StartMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMatchSimulationStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/footex.simulation.SimulationService/StartMatchSimulationStream',
            simulation__pb2.SimulateMatchRequest.SerializeToString,
            simulation__pb2.MatchEventRaw.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/footex.simulation.SimulationService/GetHealth',
            simulation__pb2.HealthRequest.SerializeToString,
            simulation__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
