// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20250608212517_matchEventsId")]
    partial class matchEventsId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("FavoriteTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteTeamId")
                        .HasDatabaseName("IX_ApplicationUser_FavoriteTeam");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FavoriteTeamId"), "btree");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_ApplicationUser_Email");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedEmail"), "btree");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUser_UserName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedUserName"), "btree");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasComment("Application users with custom profile data");
                        });
                });

            modelBuilder.Entity("Domain.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoachingStyle")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PreferredFormation")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nationality")
                        .HasDatabaseName("IX_Coach_Nationality");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nationality"), "btree");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_Coach_TeamId");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Coach_Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FirstName", "LastName"), "btree");

                    b.ToTable("Coaches", null, t =>
                        {
                            t.HasComment("Football coaches information");
                        });
                });

            modelBuilder.Entity("Domain.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Competitions", null, t =>
                        {
                            t.HasComment("Football competitions information");
                        });
                });

            modelBuilder.Entity("Domain.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayAccurateLongBalls")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayCoachId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayLongBalls")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamClearances")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamCorners")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamDribbles")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamDuels")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamDuelsWon")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamFouls")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamFreeKicks")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamGoalKicks")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("AwayTeamInMatchName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("AwayTeamLongBallsAccuracy")
                        .HasColumnType("double precision");

                    b.Property<int?>("AwayTeamOffsides")
                        .HasColumnType("integer");

                    b.Property<double?>("AwayTeamPassAccuracy")
                        .HasColumnType("double precision");

                    b.Property<int?>("AwayTeamPasses")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamPassesCompleted")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamPossession")
                        .HasColumnType("integer");

                    b.Property<long?>("AwayTeamPossessionDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<int?>("AwayTeamPossessionWon")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamRecoveries")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamRedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamSaves")
                        .HasColumnType("integer");

                    b.Property<short?>("AwayTeamScore")
                        .HasColumnType("smallint");

                    b.Property<int?>("AwayTeamSeasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamShots")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamShotsOffTarget")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamShotsOnTarget")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayTeamYellowCards")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("HomeAccurateLongBalls")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeCoachId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeLongBalls")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamClearances")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamCorners")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamDribbles")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamDuels")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamDuelsWon")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamFouls")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamFreeKicks")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamGoalKicks")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("HomeTeamInMatchName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("HomeTeamLongBallsAccuracy")
                        .HasColumnType("double precision");

                    b.Property<int?>("HomeTeamOffsides")
                        .HasColumnType("integer");

                    b.Property<double?>("HomeTeamPassAccuracy")
                        .HasColumnType("double precision");

                    b.Property<int?>("HomeTeamPasses")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamPassesCompleted")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamPossession")
                        .HasColumnType("integer");

                    b.Property<long?>("HomeTeamPossessionDurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<int?>("HomeTeamPossessionWon")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamRecoveries")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamRedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamSaves")
                        .HasColumnType("integer");

                    b.Property<short?>("HomeTeamScore")
                        .HasColumnType("smallint");

                    b.Property<int?>("HomeTeamSeasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamShots")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamShotsOffTarget")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamShotsOnTarget")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamYellowCards")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDraw")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastEventPossessingTeamName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("LastEventTimestampSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("LosingTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchStatus")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short?>("MatchWeek")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ModelSimulationStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("SimulationId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayCoachId");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("IX_Match_AwayTeam");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AwayTeamId"), "btree");

                    b.HasIndex("AwayTeamSeasonId");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("IX_Match_CreatorId");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CreatorId"), "btree");

                    b.HasIndex("HomeCoachId");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("IX_Match_HomeTeam");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeTeamId"), "btree");

                    b.HasIndex("HomeTeamSeasonId");

                    b.HasIndex("MatchStatus")
                        .HasDatabaseName("IX_Match_Status");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MatchStatus"), "btree");

                    b.HasIndex("ScheduledDateTimeUtc")
                        .HasDatabaseName("IX_Match_KickoffTime");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ScheduledDateTimeUtc"), "btree");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StadiumId")
                        .HasDatabaseName("IX_Match_StadiumId");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StadiumId"), "btree");

                    b.HasIndex("HomeTeamId", "AwayTeamId", "ScheduledDateTimeUtc")
                        .HasDatabaseName("IX_Match_Teams_Date");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("HomeTeamId", "AwayTeamId", "ScheduledDateTimeUtc"), "btree");

                    b.ToTable("Matches", null, t =>
                        {
                            t.HasComment("Football match information");
                        });
                });

            modelBuilder.Entity("Domain.Models.MatchEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("GoalsAwayTeam")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsHomeTeam")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalBlocks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCards")
                        .HasColumnType("integer");

                    b.Property<int>("TotalClearances")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCorners")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDribbles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDuels")
                        .HasColumnType("integer");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEvents")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFouls")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFreeKicks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGoalKicks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGoalkeeperSaves")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGoals")
                        .HasColumnType("integer");

                    b.Property<int>("TotalInjuries")
                        .HasColumnType("integer");

                    b.Property<int>("TotalInterceptions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOffsides")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOuts")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPasses")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPenalties")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPossessionWon")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRedCards")
                        .HasColumnType("integer");

                    b.Property<int>("TotalShots")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSubstitutions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalThrowIns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalYellowCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventsJson")
                        .HasDatabaseName("IX_MatchEvents_EventsJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EventsJson"), "gin");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("IX_MatchEvents_LastUpdated");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastUpdated"), "btree");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchEvents_MatchId");

                    b.HasIndex("GoalsHomeTeam", "GoalsAwayTeam")
                        .HasDatabaseName("IX_MatchEvents_Goals");

                    b.ToTable("MatchEvents", null, t =>
                        {
                            t.HasComment("Contains event data for matches");
                        });
                });

            modelBuilder.Entity("Domain.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("IsRead");

                    b.HasIndex("Time");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KnownName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("PreferredFoot")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short?>("ShirtNumber")
                        .HasColumnType("smallint");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("Nationality")
                        .HasDatabaseName("IX_Player_Nationality");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nationality"), "btree");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_Player_TeamId");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TeamId"), "btree");

                    b.HasIndex("FullName", "KnownName")
                        .HasDatabaseName("IX_Player_Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName", "KnownName"), "btree");

                    b.ToTable("Players", null, t =>
                        {
                            t.HasComment("Football players information");
                        });
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshToken_Token");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Token"), "btree");

                    b.HasIndex("UserId", "Revoked", "Expires")
                        .HasDatabaseName("IX_RefreshToken_Active")
                        .HasFilter("\"Revoked\" IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("UserId", "Revoked", "Expires"), "btree");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasComment("User refresh tokens");
                        });
                });

            modelBuilder.Entity("Domain.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LeagueName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("TotalRounds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Season_Active");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("IsActive"), "btree");

                    b.HasIndex("IsActive", "CurrentRound")
                        .HasDatabaseName("IX_Season_CurrentRound")
                        .HasFilter("\"IsActive\" = 'true'");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("IsActive", "CurrentRound"), "btree");

                    b.HasIndex("LeagueName", "Country", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Season_LeagueSeason");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LeagueName", "Country", "Name"), "btree");

                    b.ToTable("Seasons", null, t =>
                        {
                            t.HasComment("Football competition seasons");
                        });
                });

            modelBuilder.Entity("Domain.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Architect")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BuiltDate")
                        .HasColumnType("date");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("CostMillionsEuros")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("Facilities")
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasRoof")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("LastRenovation")
                        .HasColumnType("date");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("SurfaceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Facilities")
                        .HasDatabaseName("IX_Stadium_Facilities");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Facilities"), "gin");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Stadium_Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "btree");

                    b.HasIndex("City", "Country")
                        .HasDatabaseName("IX_Stadium_Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("City", "Country"), "btree");

                    b.ToTable("Stadiums", null, t =>
                        {
                            t.HasComment("Stadium information");
                        });
                });

            modelBuilder.Entity("Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("League")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Team_Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "btree");

                    b.HasIndex("ShortName")
                        .IsUnique()
                        .HasDatabaseName("IX_Team_ShortName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ShortName"), "btree");

                    b.HasIndex("StadiumId");

                    b.HasIndex("Country", "City")
                        .HasDatabaseName("IX_Team_Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Country", "City"), "btree");

                    b.ToTable("Teams", null, t =>
                        {
                            t.HasComment("Football teams information");
                        });
                });

            modelBuilder.Entity("Domain.Models.TeamSeasons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("IX_TeamSeasons_TeamSeason");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TeamId", "SeasonId"), "btree");

                    b.ToTable("TeamSeasons", null, t =>
                        {
                            t.HasComment("Team seasons table");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ApplicationUser", b =>
                {
                    b.HasOne("Domain.Models.Team", "FavoriteTeam")
                        .WithMany()
                        .HasForeignKey("FavoriteTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FavoriteTeam");
                });

            modelBuilder.Entity("Domain.Models.Coach", b =>
                {
                    b.HasOne("Domain.Models.Team", "Team")
                        .WithMany("Coaches")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Models.Match", b =>
                {
                    b.HasOne("Domain.Models.Coach", "AwayCoach")
                        .WithMany()
                        .HasForeignKey("AwayCoachId");

                    b.HasOne("Domain.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Match_AwayTeam");

                    b.HasOne("Domain.Models.Season", "AwayTeamSeason")
                        .WithMany()
                        .HasForeignKey("AwayTeamSeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.ApplicationUser", "Creator")
                        .WithMany("Matches")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Coach", "HomeCoach")
                        .WithMany()
                        .HasForeignKey("HomeCoachId");

                    b.HasOne("Domain.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Match_HomeTeam");

                    b.HasOne("Domain.Models.Season", "HomeTeamSeason")
                        .WithMany()
                        .HasForeignKey("HomeTeamSeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.Season", null)
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId");

                    b.HasOne("Domain.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayCoach");

                    b.Navigation("AwayTeam");

                    b.Navigation("AwayTeamSeason");

                    b.Navigation("Creator");

                    b.Navigation("HomeCoach");

                    b.Navigation("HomeTeam");

                    b.Navigation("HomeTeamSeason");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Domain.Models.MatchEvents", b =>
                {
                    b.HasOne("Domain.Models.Match", "Match")
                        .WithOne("MatchEvents")
                        .HasForeignKey("Domain.Models.MatchEvents", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Domain.Models.Notification", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Player", b =>
                {
                    b.HasOne("Domain.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Domain.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Season", b =>
                {
                    b.HasOne("Domain.Models.Competition", "Competition")
                        .WithMany("Seasons")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Domain.Models.Team", b =>
                {
                    b.HasOne("Domain.Models.Stadium", "Stadium")
                        .WithMany("Teams")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Domain.Models.TeamSeasons", b =>
                {
                    b.HasOne("Domain.Models.Season", "Season")
                        .WithMany("SeasonTeams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Team", "Team")
                        .WithMany("TeamSeasons")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamSeasons_Team");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.ApplicationUser", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Models.Competition", b =>
                {
                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Domain.Models.Match", b =>
                {
                    b.Navigation("MatchEvents");
                });

            modelBuilder.Entity("Domain.Models.Season", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("SeasonTeams");
                });

            modelBuilder.Entity("Domain.Models.Stadium", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("Coaches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");

                    b.Navigation("TeamSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
