#!/usr/bin/env pwsh

# Trust Development Certificate Script for Footex
# This script helps trust the self-signed certificate generated by the container

Write-Host "Footex HTTPS Certificate Trust Setup" -ForegroundColor Green
Write-Host "====================================" -ForegroundColor Green

# Check if running as administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")

if (-not $isAdmin) {
    Write-Host "This script needs to be run as Administrator to install certificates." -ForegroundColor Yellow
    Write-Host "Please run PowerShell as Administrator and try again." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Alternative: You can manually trust the certificate in your browser:" -ForegroundColor Cyan
    Write-Host "1. Go to https://localhost:7082" -ForegroundColor Cyan
    Write-Host "2. Click 'Advanced' on the security warning" -ForegroundColor Cyan
    Write-Host "3. Click 'Proceed to localhost (unsafe)'" -ForegroundColor Cyan
    Write-Host "4. Your browser will remember this choice" -ForegroundColor Cyan
    exit 1
}

Write-Host "Checking for certificate file..." -ForegroundColor Yellow

$certPath = ".\certs\aspnetapp.pfx"
$pemCertPath = ".\certs\aspnetapp.crt"

if (Test-Path $certPath) {
    Write-Host "Found certificate at: $certPath" -ForegroundColor Green
    
    try {
        # Import the certificate to the local machine trusted root store
        $password = ConvertTo-SecureString "00000000" -AsPlainText -Force
        Import-PfxCertificate -FilePath $certPath -CertStoreLocation Cert:\LocalMachine\Root -Password $password -Exportable
          Write-Host "Certificate successfully imported to trusted root store!" -ForegroundColor Green
        Write-Host "You can now access https://localhost:7082 without security warnings." -ForegroundColor Green
        Write-Host ""
        Write-Host "For Arc Browser users:" -ForegroundColor Cyan
        Write-Host "1. The certificate should work automatically since Arc uses Windows certificate store" -ForegroundColor Cyan
        Write-Host "2. If you still see warnings, restart Arc browser completely" -ForegroundColor Cyan
        Write-Host "3. You can also manually trust the certificate in Arc:" -ForegroundColor Cyan
        Write-Host "   - Go to https://localhost:7082" -ForegroundColor Cyan
        Write-Host "   - Click the warning icon in the address bar" -ForegroundColor Cyan
        Write-Host "   - Click 'Certificate (Invalid)' -> 'View Certificate'" -ForegroundColor Cyan
        Write-Host "   - Click 'Install Certificate' and add to 'Trusted Root Certification Authorities'" -ForegroundColor Cyan
    }
    catch {
        Write-Host "Error importing certificate: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "You may need to manually trust the certificate in your browser." -ForegroundColor Yellow
    }
}
elseif (Test-Path $pemCertPath) {
    Write-Host "Found PEM certificate at: $pemCertPath" -ForegroundColor Green
    Write-Host "Manual import required for PEM format." -ForegroundColor Yellow
    Write-Host "Please import this certificate manually to your browser's trusted certificates." -ForegroundColor Yellow
}
else {
    Write-Host "Certificate not found. Please start the development environment first:" -ForegroundColor Red
    Write-Host ".\docker-manage.ps1 dev-up" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "The certificate will be generated when the container starts." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Alternative Solutions:" -ForegroundColor Cyan
Write-Host "1. Use HTTP instead: http://localhost:5025/swagger" -ForegroundColor Cyan
Write-Host "2. Use browser flags to ignore SSL errors (not recommended for production)" -ForegroundColor Cyan
Write-Host "3. Manually accept the certificate in your browser" -ForegroundColor Cyan
Write-Host ""
Write-Host "Arc Browser Specific Instructions:" -ForegroundColor Magenta
Write-Host "If Arc browser still shows certificate warnings after running this script:" -ForegroundColor Magenta
Write-Host "1. Close Arc completely and reopen it" -ForegroundColor White
Write-Host "2. Go to https://localhost:7082" -ForegroundColor White
Write-Host "3. Click 'Not Secure' in the address bar" -ForegroundColor White
Write-Host "4. Click 'Certificate (Invalid)'" -ForegroundColor White
Write-Host "5. Click 'Details' tab, then 'Copy to File...'" -ForegroundColor White
Write-Host "6. Install it manually to 'Trusted Root Certification Authorities'" -ForegroundColor White
Write-Host "7. Alternatively, you can copy the certificate file:" -ForegroundColor White
Write-Host "   Copy-Item '.\certs\aspnetapp.crt' to your Desktop and double-click to install" -ForegroundColor Gray
